# Generated by Django 3.1.5 on 2021-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_name', models.CharField(max_length=100)),
                ('prod_brand', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('prod_availability', models.BooleanField()),
                ('prod_category', models.CharField(max_length=50)),
                ('prod_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_name', models.CharField(max_length=100)),
                ('seller_address', models.TextField()),
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_email', models.CharField(max_length=50)),
                ('seller_mobile', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
