# Generated by Django 3.1.5 on 2021-02-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbtestapp', '0002_auto_20210202_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
